name: tcrwa_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:  # for auth
  cloud_firestore:  # for storage

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:

dev_dependencies:
  flutter_launcher_icons:
  flutter_staggered_grid_view:
  flutter_spinkit:
  http:
  intl:

  multi_image_picker:
  carousel_pro:

  datetime_picker_formfield: any
  flutter_datetime_formfield: any
  flutter_datetime_picker:

  image_picker:  #pick single image
  firebase_database:
  path:
  path_provider:
  provider:
  firebase_storage:
  auto_size_text:  # put text in auto size
  flutter_speed_dial: # to put more than one floating action button
  email_validator:  # email validator

flutter_icons:
  image_path: "images/icon/TCRWA_app_icon.png"
  android: 'launcher_icon'
  ios: true

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/TCRWA_app_icon.png
    - images/top-TCRWA-logo.png
    - images/tcrwa-logo.png
    - images/home-photo-bg.jpg
    - images/My-Info.png
    - images/Gallery.png
    - images/Notice-Board.png
    - images/Helpline.png
    - images/Neighbours.png
    - images/Settings.png
    - images/back.jpg
    - images/profile-background-image.jpg
    - images/profileImgNull.png
    - images/emptyProfileImage.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
